"""
Schema definitions for Spark Streaming event processing.

This module defines the StructType schemas used to parse JSON messages from Kafka topics
in the Streamify music streaming platform. Each schema corresponds to a specific event
type generated by the Eventsim event simulator.

The schemas are used by the streaming pipeline to:
    1. Deserialize JSON messages from Kafka into structured DataFrames
    2. Enforce type safety and data validation during stream processing
    3. Enable downstream transformations and partitioning operations

Event Types:
    - listen_events: Song play events capturing user listening activity
    - page_view_events: Website navigation events tracking user page visits
    - auth_events: Authentication events recording login/logout activity
"""

from pyspark.sql.types import (
    IntegerType,
    StringType,
    DoubleType,
    StructField,
    StructType,
    LongType,
    BooleanType
)

schema = {
    # Schema for song play events - captures when users listen to music
    # Fields include song metadata (artist, song, duration), user info,
    # session details, and geographic location data
    'listen_events': StructType([
        StructField("artist", StringType(), True),
        StructField("song", StringType(), True),
        StructField("duration", DoubleType(), True),
        StructField("ts", LongType(), True),
        StructField("sessionid", IntegerType(), True),
        StructField("auth", StringType(), True),
        StructField("level", StringType(), True),
        StructField("itemInSession", IntegerType(), True),
        StructField("city", StringType(), True),
        StructField("zip", IntegerType(), True),
        StructField("state", StringType(), True),
        StructField("userAgent", StringType(), True),
        StructField("lon", DoubleType(), True),
        StructField("lat", DoubleType(), True),
        StructField("userId", LongType(), True),
        StructField("lastName", StringType(), True),
        StructField("firstName", StringType(), True),
        StructField("gender", StringType(), True),
        StructField("registration", LongType(), True)
    ]),
    # Schema for website navigation events - tracks user page visits and interactions
    # Includes HTTP request details (method, status), page info, and optional
    # song/artist data when viewing music-related pages
    'page_view_events': StructType([
        StructField("ts", LongType(), True),
        StructField("sessionId", IntegerType(), True),
        StructField("page", StringType(), True),
        StructField("auth", StringType(), True),
        StructField("method", StringType(), True),
        StructField("status", IntegerType(), True),
        StructField("level", StringType(), True),
        StructField("itemInSession", IntegerType(), True),
        StructField("city", StringType(), True),
        StructField("zip", IntegerType(), True),
        StructField("state", StringType(), True),
        StructField("userAgent", StringType(), True),
        StructField("lon", DoubleType(), True),
        StructField("lat", DoubleType(), True),
        StructField("userId", IntegerType(), True),
        StructField("lastName", StringType(), True),
        StructField("firstName", StringType(), True),
        StructField("gender", StringType(), True),
        StructField("registration", LongType(), True),
        StructField("artist", StringType(), True),
        StructField("song", StringType(), True),
        StructField("duration", DoubleType(), True)
    ]),
    # Schema for authentication events - records user login/logout activity
    # Contains session info, user details, location, and a success flag
    # indicating whether the authentication attempt was successful
    'auth_events': StructType([
        StructField("ts", LongType(), True),
        StructField("sessionId", IntegerType(), True),
        StructField("level", StringType(), True),
        StructField("itemInSession", IntegerType(), True),
        StructField("city", StringType(), True),
        StructField("zip", IntegerType(), True),
        StructField("state", StringType(), True),
        StructField("userAgent", StringType(), True),
        StructField("lon", DoubleType(), True),
        StructField("lat", DoubleType(), True),
        StructField("userId", IntegerType(), True),
        StructField("lastName", StringType(), True),
        StructField("firstName", StringType(), True),
        StructField("gender", StringType(), True),
        StructField("registration", LongType(), True),
        StructField("success", BooleanType(), True)
    ])
}
